export const USER_DETAILS = "USER_DETAILS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const FAVOURITE_LIST = "FAVOURITE_LIST";
export const SET_FAVOURITE_LIST = "SET_FAVOURITE_LIST";
export const REMOVE_FAVOURITE_LIST = "REMOVE_FAVOURITE_LIST";